project_id = "aijuacqdvrbflzwqhmvn"

[functions.analyze-document]
verify_jwt = false

[functions.analyze-medicine]
verify_jwt = false

[functions.symptom-checker]
verify_jwt = false

[functions.transcribe-consulta]
verify_jwt = false

[functions.analyze-consulta]
verify_jwt = false

[functions.image-diagnosis]
verify_jwt = false

[functions.drug-interactions]
verify_jwt = false